export const START_LOAD_TODOS = 'START_LOAD_TODOS';
export const LOAD_TODOS_SUCCESS = 'LOAD_TODOS_SUCCESS';
export const LOAD_TODOS_ERROR = 'LOAD_TODOS_ERROR';

export const START_SAVE_TODO = 'START_SAVE_TODO';
export const SAVE_TODO_SUCCESS = 'SAVE_TODO_SUCCESS';
export const SAVE_TODO_ERROR = 'SAVE_TODO_ERROR';

export const START_GET_TODO = 'START_GET_TODO';
export const GET_TODO_SUCCESS = 'GET_TODO_SUCCESS';
export const GET_TODO_ERROR = 'GET_TODO_ERROR';

export const REMOVE_TODO = 'REMOVE_TODO';

export const START_UPDATE_TODO = 'START_UPDATE_TODO';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_ERROR = 'UPDATE_TODO_ERROR';

export const CHANGE_STATUS_TODO = 'CHANGE_STATUS_TODO';

export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_ERROR = 'DELETE_TODO_ERROR';
